---
- name: Prepare all nodes
  hosts: all
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: Install required system packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - python3-docker
          - python3-setuptools
        state: present
        update_cache: yes

    - name: Install Python dependencies via apt
      apt:
        name:
          - python3-jsondiff
          - python3-yaml
          - python3-docker
        state: present
        update_cache: yes

    - name: Cleanup duplicate Docker repo files
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list"
        state: absent

    - name: Cleanup secondary duplicate Docker repo files
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/docker.list"
        state: absent

    - name: Create directory for Docker keyring
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker  # This forces the file to be 'docker.list' every time

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ssh_user }}"
        groups: docker
        append: yes

- name: Manage Docker Swarm Cluster
  hosts: all
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: Check Swarm Status and Role
      ansible.builtin.shell: |
        echo "$(docker info --format '{{ "{{" }} .Swarm.LocalNodeState {{ "}}" }}') $(docker info --format '{{ "{{" }} .Swarm.ControlAvailable {{ "}}" }}')"
      register: swarm_info_raw
      changed_when: false

    - name: Set Swarm Facts
      ansible.builtin.set_fact:
        is_active: "{{ 'active' in swarm_info_raw.stdout }}"
        is_manager: "{{ 'true' in swarm_info_raw.stdout }}"

    - name: Initialize Swarm on Primary Manager
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ manager_ip }}"
      register: swarm_init_out
      when: 
        - inventory_hostname == groups['swarm_managers'][0]
        - not is_active

    - name: Promote Worker to Manager (Via Delegation)
      ansible.builtin.command: "docker node promote {{ ansible_hostname }}"
      delegate_to: "{{ groups['swarm_managers'][0] }}"
      when: 
        - "'swarm_managers' in group_names"
        - is_active
        - not is_manager
        - inventory_hostname != groups['swarm_managers'][0]

    - name: Get Join Token (Run on Primary Manager)
      ansible.builtin.command: docker swarm join-token -q worker
      register: worker_token_cmd
      changed_when: false
      delegate_to: "{{ groups['swarm_managers'][0] }}"
      run_once: true

    - name: Set Join Token Fact
      ansible.builtin.set_fact:
        worker_token: "{{ worker_token_cmd.stdout }}"
      run_once: true

    - name: Join Worker Nodes
      community.docker.docker_swarm:
        state: join
        advertise_addr: "{{ ansible_host }}"
        join_token: "{{ worker_token }}"
        remote_addrs: ["{{ manager_ip }}:2377"]
      when: 
        - "'swarm_workers' in group_names"
        - not is_active

- name: Deploy Portainer Stack
  hosts: swarm_managers
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: Ensure Portainer data directory exists (Local VM storage)
      file:
        path: "/home/{{ ssh_user }}/portainer_data"
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0755'

    - name: Deploy Portainer stack
      community.docker.docker_stack:
        name: portainer
        state: present
        compose:
          - "/home/{{ ssh_user }}/docker-swarm/portainer-agent-stack.yml"
      when: inventory_hostname == groups['swarm_managers'][0]
      register: stack_deploy

    - name: Show stack deployment status
      debug:
        msg: "Stack deployed successfully!"
      when: stack_deploy.changed

- name: Configure Syncthing for Managers
  hosts: swarm_managers
  become: true
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: Install Syncthing
      apt:
        name: syncthing
        state: present
        update_cache: yes

    - name: Ensure Portainer data directory exists
      file:
        path: "{{ portainer_data_path }}"
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0755'

    - name: Allow Syncthing UI to be reached from the network
      ansible.builtin.replace:
        path: "/home/{{ ssh_user }}/.config/syncthing/config.xml"
        regexp: '127.0.0.1:8384'
        replace: '0.0.0.0:8384'
      notify: Restart Syncthing

    - name: Create Syncthing systemd service unit
      copy:
        dest: /etc/systemd/system/syncthing@{{ ssh_user }}.service
        content: |
          [Unit]
          Description=Syncthing - Open Source Continuous File Synchronization for %i
          After=network.target

          [Service]
          User=%i
          ExecStart=/usr/bin/syncthing -no-browser -no-restart -logflags=0
          Restart=on-failure
          SuccessExitStatus=3 4
          RestartForceExitStatus=3 4

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Syncthing
      ansible.builtin.systemd:
        name: "syncthing@{{ ssh_user }}"
        state: started
        enabled: yes
        daemon_reload: yes
